module.exports=[
    {
        text:"XCOM",
        posterUrl:"https://www.mobygames.com/images/covers/l/481144-xcom-enemy-unknown-windows-front-cover.jpg",
    },
    {
        text:"папа",
        posterUrl:"https://upload.wikimedia.org/wikipedia/ru/thumb/a/a2/The_Witcher_3-_Wild_Hunt_Cover.jpg/266px-The_Witcher_3-_Wild_Hunt_Cover.jpg",
    },
    {
        text:"дпоц",
        posterUrl:"https://upload.wikimedia.org/wikipedia/ru/thumb/a/a2/The_Witcher_3-_Wild_Hunt_Cover.jpg/266px-The_Witcher_3-_Wild_Hunt_Cover.jpg",
    }
];